### ISSUE TITLE
add item within bytecode table

### ISSUE THREAD

**Issue by luxebeng** [zkmove/zkmove#100]
to record some instruction's static information. one or two item need to added into byte code table. there are 2 candidate here.
1. field_offset of Borrow_field.
2. num_of_bytes of arith op table.

**Comment by luxebeng** [comment]
as for instruction borrow_field, alternative implementation is found and no need to add field_offset into bytecode table now.

**Comment by guangyuz** [comment]
zkmove/zkmove#95
