### ISSUE TITLE
change behaviour of Value::clone

### ISSUE THREAD

**Issue by nanne007** [zkmove/zkmove#104]
Now Value::clone make a deep_copy, which is not intuitive.

**Comment by nanne007** [comment]
mainly this code
![telegram-cloud-photo-size-5-6318900725513565642-y](https://user-images.githubusercontent.com/1456096/220513865-3b130f42-f839-4c78-95b1-0d5bbd57cc31.jpg)

**Comment by luxebeng** [comment]
clone function is added at:
  https://github.com/young-rocks/zkmove-vm/issues/49

**Comment by luxebeng** [comment]
Because Container is nested within struct Value, a deep_copy function is added for Value. and all the Value::clone() should be changed into Value::deep_copy().
```Rust
    pub fn deep_copy(&self) -> Self {
        match self {
            Self::Invalid => Self::Invalid,
            Self::U8(v) => Self::U8(*v),
            Self::U64(v) => Self::U64(*v),
            Self::U128(v) => Self::U128(*v),
            Self::Bool(v) => Self::Bool(*v),
            Self::Address(addr) => Self::Address(*addr),
            Self::Container(c) => Self::Container(c.deep_copy()),
            Self::ContainerRef(r) => Self::ContainerRef(r.copy_value()),
            Self::IndexedRef(r) => Self::IndexedRef(r.copy_value()),
        }
    }
}
```

**Comment by luxebeng** [comment]
code change is large. postpone it since there is no blocking issue by so far.
