### ISSUE TITLE
add range check chip to handle arithmetic overflow

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#135]
we already have an implementation on zkmove-lite. some of code can be reuse.

https://github.com/young-rocks/zkmove-lite/commit/8df2625fa1522627f99629ef4a9c6d395b73bab3

**Comment by luxebeng** [comment]
[young-rocks/zkmove-vm@6aa327c](https://github.com/young-rocks/zkmove-vm/commit/6aa327c0950ba989c23496863fc7a69123ee68fa)
