### ISSUE TITLE
field index or each limb of sub_index should be in the range [0, 2^LIMB_BITS)

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#52]
add query_field_index() in the constrain builder:

```
fn query_field_index() {
  if LIMB_BITS == 8 { query_byte(); }
  if LIMB_BITS == 16 { query_u16(); }
}

```
then, fix all opcodes.

**Comment by nanne007** [comment]
we also need to constraint vector len, because when get elems, it's sub_index appends the len.
