### ISSUE TITLE
Scripts and entry functions should take arguments of any type and return any values

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#64]
currently it only support simple values.

**Comment by nanne007** [comment]
arguments should support: 
``` rust
bool
integer
address
vector<bool/integer/address>
vector<vector<bool/integer/address>>
```

**Comment by guangyuz** [comment]
https://github.com/move-language/move/commit/086005ed6a2e54f2f971b77e092416a1f9248a5b

**Comment by guangyuz** [comment]
We have implemented the feature with some limitations:
- only support non-reference arguments
- only one return value with limited flattened length.
