### ISSUE TITLE
cli option '--new-args' doesn't work

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#90]
1.description
When using '--new-args', vm first runs the script with the old arguments (set by the directive 'args') and generates the 
proving/verifying keys. Then, the script is run with the new arguments and the zkp is generated/verified with the **old** proving/verifying keys.

2.reason
If there is a conditional branch or loop in the code, the execution path will not be a fixed one. 
When setup proving/verifying keys for such vm circuit, user can configure the number of execution steps and read/write 
operations (include stack ops and locals ops). Empty steps or operations will be filled if the number of the actual 
execution steps or operations is less than the configured number. Looks like the global ops configurability is missing.

**Comment by nanne007** [comment]
the main cause is that arith_op table is wrongly generated if code exists branches.
the solution to this is generate the table statically from bytecodes.

**Comment by nanne007** [comment]
besides, there're other causes which are still unknown.
for example, run loop1.move with arg=1, new-arg=2, also results to failure.

**Comment by nanne007** [comment]
https://github.com/young-rocks/zkmove-vm/pull/6 results loop1 test failure with new-args.

**Comment by nanne007** [comment]
I pushed a branch on which we can try the case.

```
git checkout loop-not-working
cargo run --release -- run -s functional-tests/tests/scripts/loop1.move --new-args 1
```
